# Generated by Django 4.1.4 on 2022-12-27 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menutag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menutag',
            name='menu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='menu.menu'),
        ),
    ]
