# Generated by Django 4.1.4 on 2022-12-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menutag_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuTag',
        ),
    ]
