# Generated by Django 4.1.4 on 2022-12-27 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_mainmenu_menu_mainmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='mainmenu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.mainmenu'),
        ),
    ]
